services:
  mongo:
    container_name: mongo-db
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./portfolio-nosql-database/mongo-data:/data/db
    networks:
      - mongo_network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
